repos:
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt -w
        language: system
        types: [go]
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run ./...
        language: system
        pass_filenames: false
        files: \\.go$
      - id: go-test
        name: go test
        entry: go test ./...
        language: system
        pass_filenames: false
        files: \\.(go|mod|sum)$
      - id: go-build
        name: go build
        entry: go build ./...
        language: system
        pass_filenames: false
        files: \\.(go|mod|sum)$
