apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    isDefault: false
    editable: true
    access: proxy

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    isDefault: false
    editable: true
    access: proxy

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    isDefault: false
    editable: true
    access: proxy
    jsonData:
      httpMethod: GET
      streamingEnabled: false
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
        filterBySpanID: false
        tags:
          - key: service.name
            value: service
          - key: service.namespace
            value: namespace
          - key: deployment.environment
            value: environment
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: "5m"
        spanEndTimeShift: "5m"
        tags:
          - key: service.name
            value: service
          - key: span.name
            value: span
          - key: status.code
            value: status
        queries:
          - name: "Span rate"
            query: "sum(rate(tempo_spanmetrics_calls_total{service=\"$service\", span_name=\"$span\"}[$__rate_interval]))"
          - name: "Span error rate"
            query: "sum(rate(tempo_spanmetrics_errors_total{service=\"$service\", span_name=\"$span\"}[$__rate_interval])) / sum(rate(tempo_spanmetrics_calls_total{service=\"$service\", span_name=\"$span\"}[$__rate_interval])) * 100"
          - name: "p95 latency"
            query: "histogram_quantile(0.95, sum(rate(tempo_spanmetrics_latency_bucket{service=\"$service\", span_name=\"$span\"}[$__rate_interval])) by (le))"
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki

  - name: Sentry
    type: grafana-sentry-datasource
    uid: sentry
    access: proxy
    url: ${GRAFANA_SENTRY_URL}
    isDefault: false
    editable: true
    jsonData:
      organization: ${GRAFANA_SENTRY_ORG}
    secureJsonData:
      authToken: ${GRAFANA_SENTRY_AUTH_TOKEN}

  - name: Alertmanager
    type: alertmanager
    uid: alertmanager
    url: http://alertmanager:9093
    isDefault: false
    editable: true
    access: proxy
    jsonData:
      implementation: prometheus

  - name: Postgres
    type: postgres
    uid: postgres
    url: postgres:5432
    user: clubhouse
    isDefault: false
    editable: true
    access: proxy
    secureJsonData:
      password: changeme
    jsonData:
      database: clubhouse
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
