apiVersion: 1

datasources:
  - name: Sentry
    type: grafana-sentry-datasource
    uid: sentry
    access: proxy
    url: ${GRAFANA_SENTRY_URL}
    isDefault: false
    editable: true
    jsonData:
      organization: ${GRAFANA_SENTRY_ORG}
    secureJsonData:
      authToken: ${GRAFANA_SENTRY_AUTH_TOKEN}
